
const Cart = () => {
    return (
        <div className=" p-5 bg-blue-400 overflow-auto" style={{ height: "85vh", width: '250px' ,resize:'horizontal'    }}>
            <div>Cart:</div>
            <div className="m-5">        <div><h1>meow</h1></div >       <div><h1>meow</h1></div>
                <div><h1>meow</h1></div>
                <div><h1>meow</h1></div>
                <div><h1>meow</h1></div>
                <div><h1>meow</h1></div>
                <div><h1>meow</h1></div>
                <div><h1>meow</h1></div>
                <div><h1>meow</h1></div>
                <div><h1>meow</h1></div>
                <div><h1>meow</h1></div>
                <div><h1>meow</h1></div>
                <div><h1>meow</h1></div>        <div><h1>meow</h1></div>
                <div><h1>meow</h1></div>
                <div><h1>meow</h1></div>
                <div><h1>meow</h1></div>
                <div><h1>meow</h1></div>
                <div><h1>meow</h1></div>
                <div><h1>meow</h1></div>
                <div><h1>meow</h1></div>
                <div><h1>meow</h1></div>
                <div><h1>meow</h1></div>
                <div><h1>meow</h1></div>
                <div><h1>meow</h1></div>
                <div><h1>meow</h1></div>
                <div><h1>meow</h1></div>
                <div><h1>meow</h1></div>
                <div><h1>meow</h1></div>
                <div><h1>meow</h1></div>
                <div><h1>meow</h1></div>
                <div><h1>meow</h1></div>
                <div><h1>meow</h1></div>
                <div><h1>meow</h1></div>
                <div><h1>meow</h1></div>
                <div><h1>meow</h1></div>
                <div><h1>meow</h1></div>
                <div><h1>meow</h1></div>
                <div><h1>meow</h1></div>
                <div><h1>meow</h1></div>
                <div><h1>meow</h1></div>
                <div><h1>meow</h1></div>
                <div><h1>meow</h1></div>
                <div><h1>meow</h1></div>
                <div><h1>meow</h1></div>
                <div><h1>meow</h1></div>
                <div><h1>meow</h1></div>
                <div><h1>meow</h1></div>
                <div><h1>meow</h1></div>
                <div><h1>meow</h1></div>
                <div><h1>meow</h1></div>
                <div><h1>meow</h1></div>
                <div><h1>meow</h1></div>
                <div><h1>meow</h1></div>
                <div><h1>meow</h1></div>
                <div><h1>meow</h1></div>
                <div><h1>meow</h1></div>
                <div><h1>meow</h1></div>
                <div><h1>meow</h1></div>
                <div><h1>meow</h1></div>
                <div><h1>meow</h1></div>
                <div><h1>meow</h1></div>
                <div><h1>meow</h1></div>
                <div><h1>meow</h1></div>
                <div><h1>meow</h1></div>
                <div><h1>meow</h1></div>
                <div><h1>meow</h1></div>
                <div><h1>meow</h1></div>
                <div><h1>meow</h1></div>
                <div><h1>meow</h1></div>
                <div><h1>meow</h1></div>
                <div><h1>meow</h1></div>
                <div><h1>meow</h1></div>
                <div><h1>meow</h1></div>
                <div><h1>meow</h1></div>
                <div><h1>meow</h1></div>
                <div><h1>meow</h1></div>
                <div><h1>meow</h1></div>
                <div><h1>meow</h1></div>
                <div><h1>meow</h1></div>
                <div><h1>meow</h1></div>
                <div><h1>meow</h1></div>
                <div><h1>meow</h1></div>
                <div><h1>meow</h1></div>
            </div>
        </div>
    )
}

export default Cart